# Generated by Django 5.0.7 on 2026-04-22 17:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_add_regularization_wfh_penalty_policy'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='attendancepenalty',
            new_name='attendance__employe_f0d4eb_idx',
            old_name='penalty_emp_date_status_idx',
        ),
        migrations.RenameIndex(
            model_name='regularizationrequest',
            new_name='attendance__employe_3db8c2_idx',
            old_name='reg_emp_date_status_idx',
        ),
        migrations.AlterField(
            model_name='attendancepenalty',
            name='date',
            field=models.DateField(help_text='The anomaly date that triggered this penalty'),
        ),
        migrations.AlterField(
            model_name='attendancepenalty',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='attendancepenalty',
            name='payroll_locked',
            field=models.BooleanField(default=False, help_text='True if payroll for this month was already processed — reversal must wait for next cycle'),
        ),
        migrations.AlterField(
            model_name='attendancepolicy',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='attendancepolicy',
            name='penalty_order',
            field=models.JSONField(default=list, help_text='Ordered list of leave types to deduct on penalty. E.g. ["PL", "LOP"]'),
        ),
        migrations.AlterField(
            model_name='attendancepolicy',
            name='regularization_window_working_days',
            field=models.PositiveIntegerField(default=3, help_text='Working days employee has to regularize before penalty is applied'),
        ),
        migrations.AlterField(
            model_name='attendancepolicy',
            name='wfh_min_lead_days',
            field=models.PositiveIntegerField(default=1, help_text='Minimum calendar days in advance WFH must be applied'),
        ),
        migrations.AlterField(
            model_name='regularizationrequest',
            name='applied_by',
            field=models.ForeignKey(blank=True, help_text='Employee or manager who submitted', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='regularizations_applied', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='regularizationrequest',
            name='attempt_number',
            field=models.PositiveSmallIntegerField(default=1, help_text='Max 3 attempts per date'),
        ),
        migrations.AlterField(
            model_name='regularizationrequest',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='regularizationrequest',
            name='penalty_reversed',
            field=models.BooleanField(default=False, help_text='True if a penalty was restored on approval'),
        ),
        migrations.AlterField(
            model_name='regularizationrequest',
            name='requested_check_in',
            field=models.TimeField(blank=True, help_text='New check-in time (optional)', null=True),
        ),
        migrations.AlterField(
            model_name='regularizationrequest',
            name='requested_check_out',
            field=models.TimeField(help_text='New check-out time (required)'),
        ),
        migrations.AlterField(
            model_name='wfhrequest',
            name='dates',
            field=models.JSONField(help_text='List of ISO date strings for WFH'),
        ),
        migrations.AlterField(
            model_name='wfhrequest',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
