# Generated by Django 5.0.7 on 2026-04-30 00:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("attendance", "0003_rename_penalty_emp_date_status_idx_attendance__employe_f0d4eb_idx_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="attendancelog",
            name="check_in_latitude",
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name="attendancelog",
            name="check_in_longitude",
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name="attendancelog",
            name="check_in_accuracy_m",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="attendancelog",
            name="check_in_distance_m",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="attendancelog",
            name="check_in_geofence_ok",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="attendancelog",
            name="check_out_latitude",
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name="attendancelog",
            name="check_out_longitude",
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name="attendancelog",
            name="check_out_accuracy_m",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="attendancelog",
            name="check_out_distance_m",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="attendancelog",
            name="check_out_geofence_ok",
            field=models.BooleanField(blank=True, null=True),
        ),
    ]

