export DJANGO_SETTINGS_MODULE=
export DJANGO_DEBUG=
export DJANGO_ALLOWED_HOSTS=
export DJANGO_SECRET_KEY=

export DATABASE_URL=
export REDIS_URL=
export CELERY_RESULT_BACKEND=
export RABBITMQ_URL=

export JWT_ACCESS_TOKEN_LIFETIME_MINUTES=
export JWT_REFRESH_TOKEN_LIFETIME_DAYS=

export CORS_ALLOWED_ORIGINS=
export CORS_ALLOW_ALL_ORIGINS=

export INTERNAL_API_TOKEN=

export SLACK_WEBHOOK_URL=

export EMAIL_HOST=
export EMAIL_PORT=
export EMAIL_HOST_USER=
export EMAIL_HOST_PASSWORD=
export DEFAULT_FROM_EMAIL=

export LLM_PROVIDER=
export LLM_MODEL=
export OPENAI_API_KEY=
export ANTHROPIC_API_KEY=
export GEMINI_API_KEY=
export GOOGLE_API_KEY=

export OLLAMA_BASE_URL=
export OLLAMA_MODEL=
export OLLAMA_API_KEY=

export EMBEDDING_PROVIDER=
export EMBEDDING_MODEL=
export OLLAMA_EMBED_MODEL=

export VITE_API_URL=

