# Generated by Django 5.0.7 on 2026-04-22 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_add_renotify_fields'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='inappnotification',
            new_name='notificatio_recipie_46ef42_idx',
            old_name='notif_recipient_read_idx',
        ),
        migrations.RenameIndex(
            model_name='inappnotification',
            new_name='notificatio_request_a5659c_idx',
            old_name='notif_requester_idx',
        ),
    ]
