# Generated by Django 5.0.7 on 2026-04-09 13:03

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("ai", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="chatmessage",
            options={"ordering": ["created_at", "id"]},
        ),
        migrations.AlterModelOptions(
            name="chatsummary",
            options={"ordering": ["-created_at", "-id"]},
        ),
        migrations.RenameIndex(
            model_name="chatmessage",
            new_name="ai_chatmess_session_d95756_idx",
            old_name="ai_chatmes_sessio_9a4249_idx",
        ),
        migrations.RenameIndex(
            model_name="chatmessage",
            new_name="ai_chatmess_session_e9dbfc_idx",
            old_name="ai_chatmes_sessio_34d9ed_idx",
        ),
        migrations.RenameIndex(
            model_name="chatsession",
            new_name="ai_chatsess_user_id_c2886b_idx",
            old_name="ai_chatses_user_id_8b3e5c_idx",
        ),
        migrations.RenameIndex(
            model_name="chatsummary",
            new_name="ai_chatsumm_session_432a3d_idx",
            old_name="ai_chatsum_sessio_0b9605_idx",
        ),
        migrations.RenameIndex(
            model_name="chatsummary",
            new_name="ai_chatsumm_session_e3e9ea_idx",
            old_name="ai_chatsum_sessio_3c49ff_idx",
        ),
    ]
