# Generated by Django 5.0.7 on 2026-04-13 10:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("employees", "0002_alter_user_options_alter_user_managers_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="PayrollSlip",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("period_year", models.IntegerField()),
                ("period_month", models.IntegerField()),
                (
                    "gross_pay",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "net_pay",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payroll_slips",
                        to="employees.employee",
                    ),
                ),
            ],
            options={
                "ordering": ["-period_year", "-period_month", "-created_at"],
                "unique_together": {("employee", "period_year", "period_month")},
            },
        ),
    ]
