# Generated by Django 5.0.7 on 2026-04-24 00:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("employees", "0002_alter_user_options_alter_user_managers_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ReportSnapshot",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("report_key", models.CharField(max_length=200)),
                ("as_of_date", models.DateField()),
                ("params", models.JSONField(blank=True, default=dict)),
                ("payload", models.JSONField()),
                ("generated_at", models.DateTimeField(auto_now=True)),
            ],
            options={},
        ),
        migrations.AddConstraint(
            model_name="reportsnapshot",
            constraint=models.UniqueConstraint(
                fields=("report_key", "as_of_date"), name="uniq_report_snapshot_key_date"
            ),
        ),
        migrations.AddIndex(
            model_name="reportsnapshot",
            index=models.Index(fields=["report_key", "-as_of_date"], name="report_snapshot_key_asof_idx"),
        ),
    ]

