# Generated by Django 5.0.7 on 2026-04-23 10:24

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("employees", "0002_alter_user_options_alter_user_managers_and_more"),
        ("upskilling", "0002_draftroadmap"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="draftroadmap",
            name="unique_draft_per_employee_skill_status",
        ),
        migrations.AlterUniqueTogether(
            name="draftroadmap",
            unique_together={("employee", "skill_name", "status")},
        ),
    ]
