# Generated by Django 5.0.7 on 2026-04-09 13:03

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("rag", "0002_initial"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="policychunk",
            new_name="rag_policyc_version_0b0928_idx",
            old_name="rag_policyc_version_ee9b77_idx",
        ),
        migrations.RenameIndex(
            model_name="policyversion",
            new_name="rag_policyv_documen_6e251e_idx",
            old_name="rag_policyv_documen_1089c9_idx",
        ),
        migrations.RenameIndex(
            model_name="ragdocument",
            new_name="rag_ragdocu_title_149f9c_idx",
            old_name="rag_ragdoc_title_7cf1b5_idx",
        ),
    ]
