# Generated by Django 5.0.7 on 2026-04-30 00:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("employees", "0003_reportsnapshot"),
    ]

    operations = [
        migrations.CreateModel(
            name="FeedPost",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("text", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "author",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="feed_posts", to="employees.employee"),
                ),
                (
                    "kudos_to",
                    models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="kudos_received", to="employees.employee"),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="FeedPostImage",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("image", models.ImageField(blank=True, null=True, upload_to="feed/")),
                ("image_url", models.URLField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "post",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="images", to="feed.feedpost"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="FeedPostLike",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "employee",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="feed_likes", to="employees.employee"),
                ),
                (
                    "post",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="likes", to="feed.feedpost"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="FeedComment",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("text", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "author",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="feed_comments", to="employees.employee"),
                ),
                (
                    "post",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="comments", to="feed.feedpost"),
                ),
            ],
            options={
                "ordering": ["created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="feedpost",
            index=models.Index(fields=["-created_at"], name="feed_post_created_idx"),
        ),
        migrations.AddIndex(
            model_name="feedpostimage",
            index=models.Index(fields=["post", "-created_at"], name="feed_img_post_created_idx"),
        ),
        migrations.AddConstraint(
            model_name="feedpostlike",
            constraint=models.UniqueConstraint(fields=("post", "employee"), name="uniq_feed_like_post_employee"),
        ),
        migrations.AddIndex(
            model_name="feedpostlike",
            index=models.Index(fields=["post", "-created_at"], name="feed_like_post_created_idx"),
        ),
        migrations.AddIndex(
            model_name="feedpostlike",
            index=models.Index(fields=["employee", "-created_at"], name="feed_like_emp_created_idx"),
        ),
        migrations.AddIndex(
            model_name="feedcomment",
            index=models.Index(fields=["post", "created_at"], name="feed_comment_post_created_idx"),
        ),
    ]

