# Generated by Django 5.0.7 on 2026-04-30 00:00

from django.db import migrations


def seed_demo_feed(apps, schema_editor):
    Employee = apps.get_model("employees", "Employee")
    User = apps.get_model("employees", "User")
    FeedPost = apps.get_model("feed", "FeedPost")
    FeedPostImage = apps.get_model("feed", "FeedPostImage")
    FeedPostLike = apps.get_model("feed", "FeedPostLike")
    FeedComment = apps.get_model("feed", "FeedComment")

    employees = list(
        Employee.objects.filter(is_active=True)
        .select_related("user", "department")
        .order_by("id")[:20]
    )
    if not employees:
        return

    if FeedPost.objects.exists():
        return

    imgs = [
        "https://images.unsplash.com/photo-1521737604893-d14cc237f11d?auto=format&fit=crop&w=1200&q=70",
        "https://images.unsplash.com/photo-1522071820081-009f0129c71c?auto=format&fit=crop&w=1200&q=70",
        "https://images.unsplash.com/photo-1519389950473-47ba0277781c?auto=format&fit=crop&w=1200&q=70",
        "https://images.unsplash.com/photo-1522202176988-66273c2fd55f?auto=format&fit=crop&w=1200&q=70",
    ]

    def emp_name(e):
        try:
            return e.user.name or "Someone"
        except Exception:
            return "Someone"

    posts = []
    e0 = employees[0]
    e1 = employees[1] if len(employees) > 1 else employees[0]
    e2 = employees[2] if len(employees) > 2 else employees[0]
    e3 = employees[3] if len(employees) > 3 else employees[0]
    e4 = employees[4] if len(employees) > 4 else employees[0]

    posts.append(
        FeedPost.objects.create(
            author=e0,
            text="Weekly wins: shipped the new Reports performance improvements. Dashboards now load instantly 🚀",
        )
    )
    posts.append(
        FeedPost.objects.create(
            author=e1,
            text="Kudos to the team for closing out the sprint with zero critical bugs. Amazing collaboration!",
            kudos_to=e2,
        )
    )
    posts.append(
        FeedPost.objects.create(
            author=e3,
            text="Sharing some snapshots from today’s team huddle. Great energy and alignment.",
        )
    )
    posts.append(
        FeedPost.objects.create(
            author=e4,
            text="What’s one skill you’re learning this week? Drop it below and I’ll share a roadmap idea.",
        )
    )

    for i, p in enumerate(posts):
        if i < len(imgs):
            FeedPostImage.objects.create(post=p, image_url=imgs[i])

    for p in posts:
        for e in employees[:8]:
            if e.id != p.author_id:
                FeedPostLike.objects.get_or_create(post=p, employee=e)

    FeedComment.objects.create(
        post=posts[0],
        author=e2,
        text="Huge improvement in load times. This is going to make leadership reviews so much smoother.",
    )
    FeedComment.objects.create(
        post=posts[0],
        author=e3,
        text="Nice! Especially the daily precompute approach.",
    )
    FeedComment.objects.create(
        post=posts[1],
        author=e2,
        text=f"Thanks {emp_name(e1)}! Feeling motivated.",
    )
    FeedComment.objects.create(
        post=posts[3],
        author=e0,
        text="I’m focusing on system design + AI product thinking.",
    )


def unseed_demo_feed(apps, schema_editor):
    FeedPost = apps.get_model("feed", "FeedPost")
    FeedPost.objects.all().delete()


class Migration(migrations.Migration):
    dependencies = [
        ("feed", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(seed_demo_feed, reverse_code=unseed_demo_feed),
    ]

